services:
  nest-app:
    build:
      context: .
    ports:
      - "4000:3000"
    env_file:
      - .env
    command: sh -c 'npx prisma db push && yarn build && yarn start:prod'
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:17.5
    ports:
      - "5433:5432"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d traffic_db"]
      timeout: 3s
      interval: 5s
      retries: 3
  redis:
    image: redis:7
    ports:
      - "6380:6379"
