name: Deploy to Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          PROJECT_PATH: ${{ secrets.PROJECT_PATH }}
          
        run: |
          # Setup SSH
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
          
          # Define deployment directory
          DEPLOY_DIR="/home/$SSH_USERNAME/$PROJECT_PATH"
          
          # Connect and deploy
          ssh -i ~/.ssh/deploy_key $SSH_USERNAME@$SSH_HOST << 'ENDSSH'
            set -e
            
            # Navigate to deployment directory
            cd $PROJECT_PATH
            
            # Pull latest code
            if [ -d .git ]; then
              git fetch origin
              git reset --hard origin/main
            else
              git clone ${{ github.server_url }}/${{ github.repository }} .
              git checkout main
            fi
            
            # Create .env file
            cat > .env << 'EOF'
          ${{ secrets.NODE_ENV }}
          # Add more environment variables as needed
          EOF
            
            # Stop existing containers
            docker-compose down
            
            # Build and start containers
            docker-compose up -d --build
            
            # Wait for database to be ready
            echo "Waiting for database to be ready..."
            sleep 10
            
            # Run Prisma migrations
            docker-compose exec -T app yarn prisma migrate deploy
            
            # Generate Prisma Client
            docker-compose exec -T app yarn prisma generate
            
            # Show container status
            docker-compose ps
            
            echo "Deployment completed successfully!"
          ENDSSH
          
          # Cleanup
          rm -f ~/.ssh/deploy_key